### ISSUE TITLE
Prebuilt themes?

### ISSUE THREAD

**Issue by nombrekeff** [nombrekeff/cli-badges#3]
Maybe some sort of theming could be implemented, instead of passing each individual option, we could maybe just pass a theme option ie: `{ theme: 'grey-black' }` or similar.

**Comment by nombrekeff** [comment]
I've thought about a way the theme API could work:

```js
console.log(
    badge.green('theme', 'green'),
    badge.blue('theme', 'blue'),
    badge.red('theme', 'red'),
    badge.yellow('theme', 'yellow'),
    badge.magenta('theme', 'magenta'),
    badge.cyan('theme', 'cyan'),
    badge.theme('cyan')('theme', 'cyan'),
);

console.log(
    badge.green.inversed('theme', 'green'),
    badge.blue.inversed('theme', 'blue'),
    badge.red.inversed('theme', 'red'),
    badge.yellow.inversed('theme', 'yellow'),
    badge.magenta.inversed('theme', 'magenta'),
    badge.cyan.inversed('theme', 'cyan'),
    badge.theme('cyan').inversed('theme', 'cyan'),
);
```

**Comment by haideralipunjabi** [comment]
I have added this in the Python Version @haideralipunjabi/cli-badges . I also added options to allow users to define themes, and load themes from JSON file

**Comment by nombrekeff** [comment]
Ohh awesome, I will check that out as well! Maybe implement the defining themes functionality :smile:

**Comment by nombrekeff** [comment]
I ended up changing `invert` for `swap`, I think it makes more sense. And there is already an **inverse** style, so it might create confusion. What do you think?

I do like the approach you have done, I did not think about the texts being part of the theme. Wonderfull 👍

**Comment by haideralipunjabi** [comment]
Yes, `swap` seems better. I will also make the change

**Comment by nombrekeff** [comment]
Cool, I just published a new version with support for themes 🎉

**Comment by nombrekeff** [comment]
Thanks for the inspiration @haideralipunjabi, I got some ideas from your approach 💯 

BTW do you have a discord? I could set up a group with you and Delta so we can discuss new features and such

**Comment by haideralipunjabi** [comment]
Yeah I do, same username there as well

**Comment by nombrekeff** [comment]
Nice, I need the #id as well it seems, mine is nombrekeff#6034

**Comment by haideralipunjabi** [comment]
I have sent the request
