### ISSUE TITLE
Image doesn't match code in README

### ISSUE THREAD

**Issue by haideralipunjabi** [nombrekeff/cli-badges#7]
In the [README.md](README.md) you use the following code:

```javascript
const { badge } = require('cli-badges');

const failedBadge = badge('failed', '2', { messageBg: 'red' });
const skippedBadge = badge('skipped', '1', {
  messageBg: 'yellow',
  messageColor: 'black',
});
const successBadge = badge('success', '8', {
  messageBg: 'green',
  messageColor: 'black',
});

console.log(failedBadge, successBadge, skippedBadge);
```

and have attached the following image:

![](https://github.com/nombrekeff/cli-badges/raw/master/output-example.png)

The colour of the message for `skippedBadge` and `successBadge` should be `black` and not `white`

**Comment by nombrekeff** [comment]
Ohh yeah, sorry about that! I did it quickly and missed that!

I will fix it shortly! Thanks for the issue!

**Comment by haideralipunjabi** [comment]
If you don't mind my asking, how do you make these images?

**Comment by nombrekeff** [comment]
I'm doing them with Figma at the moment, I wanted to make screenshots but they were too low resolution. 

I will try adding screenshots when I find some way of increasing the resolution.

**Comment by haideralipunjabi** [comment]
That's nice. I am trying to port this project over to python and wanted to know how you made the images. I ended up using Inkscape to make them, but Figma seems like a great option.

**Comment by nombrekeff** [comment]
That's awesome, let me know if/when you port it, and I will link it in the readme as an alternative for other languages :smile:

Yeah, Figma is a nice option. Works great and can be shared with collaborators!

**Comment by haideralipunjabi** [comment]
Yes, here you go 
https://github.com/haideralipunjabi/cli-badges

**Comment by nombrekeff** [comment]
Great, I will link it shortly! Great work!

Could you add some sort of attribution? Just a little something explaining you were inspired by my project. 

Also, we could work in parallel if you want, making sure both projects have the same features.

**Comment by haideralipunjabi** [comment]
Yes sure I will edit it. 

We can try to work in parallel. I will keep watching your project for new features, and implement them in mine.

**Comment by nombrekeff** [comment]
I have gotten some inspiration from yours already, I will change the options to match the way you've done them. I think they are more readable in table format.

I'm also going to make styles an array as you have, I did not think about that. 

Maybe even the link per segment, a link for the label, and for the message.
