### ISSUE TITLE
can I port this to Deno and TS?

### ISSUE THREAD

**Issue by Delta456** [nombrekeff/cli-badges#8]
Hey!

I am learning Deno and TS and I want to port this project as it is very good and I want to use this as a base to extend my knowledge of Deno and TS. I hope you will not mind!

Thanks

(I know I shouldn't had made an issue but this is the fastest way of getting an answer ;) )

**Comment by nombrekeff** [comment]
Hey!
That would be awesome! Just remember to add proper attribution and a link back to this project.

I can also help you with TS if you have any issue :)

If more people are interested in this project we could make an org and host all the ports there, there is already a python port as well.

**Comment by Delta456** [comment]
@nombrekeff sure thanks

**Comment by nombrekeff** [comment]
Let me know when you have something done and I will link it in the main project

**Comment by Delta456** [comment]
sure

**Comment by Delta456** [comment]
do you use discord? I can get touch with you. Mine is `Delta231#8601`.

**Comment by nombrekeff** [comment]
Yup, I have discord. nombrekeff#6034

I'm at work at the moment, I will get in touch when I finish for the day!
